#!/bin/bash
#küsib mitmes kuu on
echo -e "Sisesta kuu number: "
#salvestab kuu numbri
read kuu
#kontrollib kas millisele kuule number kuulub
if test $kuu -eq 1 -o $kuu -eq 2 -o $kuu -eq 12
then
	echo "Praegu on talv"
elif test $kuu -ge 3 -a $kuu -le 5
then
	echo "Praegu on kevad"
elif test $kuu -ge 6 -a $kuu -le 8
then
	echo "Praegu on suvi"
elif test $kuu -ge 9 -a $kuu -le 11
then
	echo "Praegu on sügis"
else
#kui kuule ei vasta mitte ükski number väljastab veateate
	echo "Sisestatud kuule ei vasta ükski number"
fi
#skripti lõpp
