#!/bin/bash
#salvestab aja väärtuse 24 tunni formaadis võttes süsteemi kellast aja
aeg=`date +%H`
#kontrollib millisele vahemikule aeg vastab ja annab vastava teate
#ning ütleb lõppu kasutaja nime
if [ $aeg -ge 6 -a $aeg -lt 12 ]; then
	echo "Tere hommikust $(whoami)!"
elif [ $aeg -ge 12 -a $aeg -lt 18 ]; then
	echo "Tere päevast $(whoami)!"
elif [ $aeg -ge 18 -a $aeg -lt 22 ]; then
	echo "Tere õhtust $(whoami)!"
elif [ $aeg -ge 22 -a $aeg -lt 24 ] || [ $aeg -ge 0 -a $aeg -lt 6 ]; then
	echo "Head ööd $(whoami)!"
else
#palub kasutajal sisestada sobilik number
	echo "Sisesta number 0 kuni 24"
fi 
# skripti lõpp
