#!/bin/bash
#
# paarsuse kontroll
#
echo -n "Sisesta suvaline täisarv: "
read arv
# arvutamine jääk 2-ga jagamisel
jaak=$(( $arv % 2 ))
# 4 % 2 => 0 -> siis arv on paaris
if [ $jaak -eq 0 ]
then 
  echo "$arv on paaris"
else
 echo "$arv on paaritu"
fi
# tingimuse kontroll on lõppenud
