#!/bin/bash
#

osch=0
echo "1. Unix (Sun OS)"
echo "2. Linux (Red Hat)"

echo -n "Select your os choice [1 or 2]? "
read osch

if [ $osch -eq 1 ] ; then
	echo "You picked up Unix (Sun OS)"
else #### nested if i.e if within if #####
	if [ $osch -eq 2 ] ; then
		echo "You picked up Linux (Red Hat)"
	else
		echo "Why you have to be mad it's only an OS?"
		fi
	fi
 
