#!/bin/bash
#liidetakse paarisarvud 0 kuni 10
summa=0
for (( arv=1; arv<11; arv++ ))
do
	jaak=$(($arv % 2))
	if [ $jaak -eq 0 ]; then
		summa=$(($summa + $arv))
#väljastab kõik vahevastused
		echo $summa
	fi
done
#väljastab viimase summa
echo "Arvude vahemikus 1 kuni 10 (kaasaarvatud) paarisarvude summa on: $summa"
#skripti lõpp
