#!/bin/bash
# arvutab ridade arvu
for (( i=1; i <= 5; i++ ))
do 
# arvutab märkide arvu reas
	for ((j =1 ; j<=5; j++ ))
	do
# defineerib väljastatava märgi väärtuse
		echo -n "*"
	done
#teeb uue rea
	echo ""
done
#skripti lõpp
